/** Shared icons via FontAwesome - use across Dashboard, Settings, Chatbox, etc. */
const fa = (cls) => <i className={`${cls} w-5 text-center`} />;

export const Icons = {
  Dashboard: () => fa('fas fa-house'),
  Activity: () => fa('fas fa-bolt'),
  Analytics: () => fa('fas fa-chart-bar'),
  Auth: () => fa('fas fa-lock'),
  Settings: () => fa('fas fa-gear'),
  Chatbox: () => fa('fas fa-comment-dots'),
  Credits: () => fa('fas fa-heart'),
  About: () => fa('fas fa-circle-info'),
  Invite: () => fa('fas fa-user-plus'),
  UserAdd: () => fa('fas fa-user'),
  Calendar: () => fa('fas fa-calendar'),
  Users: () => fa('fas fa-users'),
  Save: () => fa('fas fa-floppy-disk'),
  Trash: () => fa('fas fa-trash-can'),
  Plus: () => fa('fas fa-plus'),
  Copy: () => fa('fas fa-copy'),
  Log: () => fa('fas fa-file-lines'),
  Globe: () => fa('fas fa-globe'),
  Play: () => fa('fas fa-play'),
  Pause: () => fa('fas fa-pause'),
  Stop: () => fa('fas fa-circle-stop'),
  Music: () => fa('fas fa-music'),
  ChevronUp: () => fa('fas fa-chevron-up'),
  ChevronDown: () => fa('fas fa-chevron-down'),
  Loop: () => fa('fas fa-rotate'),
  Star: () => fa('fas fa-star'),
  StarOutline: () => fa('far fa-star'),
  Lobby: () => fa('fas fa-earth-americas'),
  Website: () => fa('fas fa-browser'),
};
